# This is a basic workflow to help you get started with Actions

name: OpenHD Image Writer

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "qml" branch
  push:
    branches: [ "qml" ]
  pull_request:
    branches: [ "qml" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install -y --no-install-recommends libgnutls28-dev build-essential devscripts debhelper cmake git libarchive-dev libcurl4-openssl-dev qtbase5-dev qtbase5-dev-tools qtdeclarative5-dev libqt5svg5-dev qttools5-dev libssl-dev qml-module-qtquick2 qml-module-qtquick-controls2 qml-module-qtquick-layouts qml-module-qtquick-templates2 qml-module-qtquick-window2 qml-module-qtgraphicaleffects
          mkdir build
          ls -a
          cp -r `ls -A | grep -v "build"` build
          debuild -uc -us
          ls -a
          cd ..
          ls -a
      - name: Upload to Github
        uses: 'actions/upload-artifact@v2'
        with:
          name: "OpenHD Image Writer"
          path: |
            *.deb
          if-no-files-found: error