name: OpenHD Image Writer Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==2.1.*'
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win32_mingw81'
        tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
        setup-python: false

    - name: Install dependencies
      run: |
        choco install -y openssl
        choco install -y nsis

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=C:/Qt/5.12.11/mingw*_32/lib/cmake -S ../src
        mingw32-make

    - name: Sign Installer
      if: success()
      run: |
        # Sign the installer here if you have a proper code signing certificate and signtool.exe installed
