name: OpenHD Image Writer Windows
on:
  push:
  pull_request:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win32_mingw81'
        tools: 'tools_cmake,qt.tools.cmake tools_openssl_x86 tools_mingw,qt.tools.win32_mingw810 tools_ninja,qt.tools.ninja tools_ifw tools_qtcreator,qt.tools.qtcreator'
        aqtversion: '==3.1.*'
        setup-python: 'true'
        install-deps: 'true'
        cache: 'true'
        cache-key-prefix: 'install-qt-action'
        dir: ${{ github.workspace }}/qt/

    - name: Install dependencies
      run: |
        choco install -y nsis openssl

    - name: Configure CMake & Build
      run: |
        tree ${{ github.workspace }}/qt
        cmake -S src -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release
        cmake --build build -- -j2
        
    - name: Sign Installer
      if: success()
      run: |
        # Sign the installer here if you have a proper code signing certificate and signtool.exe installed
