# This is a basic workflow to help you get started with Actions

name: OpenHD Image Writer Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "qml" branch
  push:
    branches: [ "qml" ]
  pull_request:
    branches: [ "qml" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
 
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.11'
          host: 'windows'
          target: 'desktop'
          dir: '${{github.workspace}}/qt/'
          install-deps: 'true'
          tools: 'tools_openssl_src'
          
      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          dir
          cmake src
          dir
          make
          make install
          cd deploy
          dir
          cd ..
          dir
      - name: Upload to Github
        uses: 'actions/upload-artifact@v2'
        with:
          name: "OpenHD Image Writer"
          path: |
            deploy/*.exe
          if-no-files-found: error
