name: OpenHD Image Writer Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        choco install -y qt5 --params "/InstallDir:C:\Qt" 
        choco install -y mingw 
        choco install -y openssl.light
        choco install -y nsis
    - name: Configure CMake
      run: |
        mkdir build && cd build
        cmake -G "MinGW Makefiles" .. -DCMAKE_PREFIX_PATH=C:\Qt\5.*\mingw81_32\lib\cmake
    - name: Build
      run: |
        cd build
        mingw32-make
    - name: Create Installer
      run: |
        cd build
        makensis rpi-imager.nsi
