name: OpenHD Image Writer Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==2.1.*'
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win32_mingw81'
        tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator tools_cmake,3.23.2,qt.tools.cmake tools_mingw,8.1.0,qt.tools.win32_mingw810 tools_ninja,1.10.2,qt.tools.ninja'
        setup-python: 'true'
        install-deps: 'true'
        cache: 'true'
        cache-key-prefix: 'install-qt-action'
        dir: ${{ github.workspace }}/qt/

    - name: Install dependencies
      run: |
        #choco install -y openssl.light
        choco install -y nsis

    - name: Configure CMake & Build
      run: |
        #cmake -S src -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release
        cmake --build build -- -j2
        
    - name: Sign Installer
      if: success()
      run: |
        # Sign the installer here if you have a proper code signing certificate and signtool.exe installed
