name: OpenHD Image Writer Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v1
      with:
        version: '5.12.11'
        target: desktop
        toolchain: msvc2017_64

    - name: Install dependencies
      run: |
        choco install -y openssl
        choco install -y nsis

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=C:/Qt/5.12.11/msvc2017_64/lib/cmake

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Sign Installer
      if: success()
      run: |
        # Sign the installer here if you have a proper code signing certificate and signtool.exe installed
